name: menzo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  iconly: ^1.0.1
  smooth_page_indicator: ^1.0.0
  firebase_auth: ^4.16.0

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/img/
  - assets/img/self_care/
  - assets/img/counseling/
  - assets/img/home/

